// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EzyFix.DAL.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<ExamGradingCriterion> ExamGradingCriteria { get; set; }

    public virtual DbSet<ExamKeyword> ExamKeywords { get; set; }

    public virtual DbSet<GradingDetail> GradingDetails { get; set; }

    public virtual DbSet<GradingResult> GradingResults { get; set; }

    public virtual DbSet<Keyword> Keywords { get; set; }

    public virtual DbSet<Lecturer> Lecturers { get; set; }

    public virtual DbSet<LecturerSubject> LecturerSubjects { get; set; }

    public virtual DbSet<ScoreColumn> ScoreColumns { get; set; }

    public virtual DbSet<Semester> Semesters { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-8ODA32BV\\KIETLTSE184654;Initial Catalog=final_prn232;User ID=sa;Password=1234567890");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__Assignme__DA891814051AD56B");

            entity.ToTable("Assignment");

            entity.Property(e => e.AssignmentId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("assignment_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Deadline)
                .HasColumnType("datetime")
                .HasColumnName("deadline");
            entity.Property(e => e.ExamId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("exam_id");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("file_path");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.StudentId)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("student_id");
            entity.Property(e => e.SubmissionDate)
                .HasColumnType("datetime")
                .HasColumnName("submission_date");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Exam).WithMany(p => p.Assignments)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Assignmen__exam___59063A47");

            entity.HasOne(d => d.Student).WithMany(p => p.Assignments)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Assignmen__stude__5812160E");
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.ExamId).HasName("PK__Exam__9C8C7BE9527237D6");

            entity.ToTable("Exam");

            entity.Property(e => e.ExamId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("exam_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.ExtractedPath)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("extracted_path");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("file_path");
            entity.Property(e => e.LecturerSubjectId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("lecturer_subject_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UploadedAt)
                .HasColumnType("datetime")
                .HasColumnName("uploadedAt");

            entity.HasOne(d => d.LecturerSubject).WithMany(p => p.Exams)
                .HasForeignKey(d => d.LecturerSubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Exam__lecturer_s__534D60F1");
        });

        modelBuilder.Entity<ExamGradingCriterion>(entity =>
        {
            entity.HasKey(e => e.CriteriaId).HasName("PK__ExamGrad__401F949D6CCF0428");

            entity.Property(e => e.CriteriaId).HasColumnName("criteria_id");
            entity.Property(e => e.ColumnId).HasColumnName("column_id");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.ExamId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("exam_id");
            entity.Property(e => e.MaxMark)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("max_mark");

            entity.HasOne(d => d.Column).WithMany(p => p.ExamGradingCriteria)
                .HasForeignKey(d => d.ColumnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExamGradi__colum__571DF1D5");

            entity.HasOne(d => d.Exam).WithMany(p => p.ExamGradingCriteria)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExamGradi__exam___5629CD9C");
        });

        modelBuilder.Entity<ExamKeyword>(entity =>
        {
            entity.HasKey(e => e.ExamKeywordId).HasName("PK__ExamKeyw__F9DC44C9DA869D2D");

            entity.ToTable("ExamKeyword");

            entity.Property(e => e.ExamKeywordId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("examKeyword_id");
            entity.Property(e => e.ExamId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("exam_id");
            entity.Property(e => e.KeywordId).HasColumnName("keyword_id");

            entity.HasOne(d => d.Exam).WithMany(p => p.ExamKeywords)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExamKeywo__exam___5441852A");

            entity.HasOne(d => d.Keyword).WithMany(p => p.ExamKeywords)
                .HasForeignKey(d => d.KeywordId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ExamKeywo__keywo__5535A963");
        });

        modelBuilder.Entity<GradingDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__GradingD__38E9A224518CE962");

            entity.ToTable("GradingDetail");

            entity.Property(e => e.DetailId).HasColumnName("detail_id");
            entity.Property(e => e.ColumnId).HasColumnName("column_id");
            entity.Property(e => e.Mark)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("mark");
            entity.Property(e => e.ScoreId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("score_id");

            entity.HasOne(d => d.Column).WithMany(p => p.GradingDetails)
                .HasForeignKey(d => d.ColumnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GradingDe__colum__5CD6CB2B");

            entity.HasOne(d => d.Score).WithMany(p => p.GradingDetails)
                .HasForeignKey(d => d.ScoreId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GradingDe__score__5BE2A6F2");
        });

        modelBuilder.Entity<GradingResult>(entity =>
        {
            entity.HasKey(e => e.ResultId).HasName("PK__GradingR__AFB3C316C9F23B79");

            entity.ToTable("GradingResult");

            entity.Property(e => e.ResultId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("result_id");
            entity.Property(e => e.AssignmentId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("assignment_id");
            entity.Property(e => e.CheckedAt)
                .HasColumnType("datetime")
                .HasColumnName("checkedAt");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.LecturerId)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("lecturer_id");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .HasColumnName("note");
            entity.Property(e => e.TotalMark)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("total_mark");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Assignment).WithMany(p => p.GradingResults)
                .HasForeignKey(d => d.AssignmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GradingRe__assig__5AEE82B9");

            entity.HasOne(d => d.Lecturer).WithMany(p => p.GradingResults)
                .HasForeignKey(d => d.LecturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GradingRe__lectu__59FA5E80");
        });

        modelBuilder.Entity<Keyword>(entity =>
        {
            entity.HasKey(e => e.KeywordId).HasName("PK__Keyword__03E8D7CFE5EF6E0C");

            entity.ToTable("Keyword");

            entity.Property(e => e.KeywordId).HasColumnName("keyword_id");
            entity.Property(e => e.Word)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("word");
        });

        modelBuilder.Entity<Lecturer>(entity =>
        {
            entity.HasKey(e => e.LecturerId).HasName("PK__Lecturer__D4D1DAB1CC25A84F");

            entity.ToTable("Lecturer");

            entity.HasIndex(e => e.Email, "UQ__Lecturer__AB6E61643BDB4DEC").IsUnique();

            entity.Property(e => e.LecturerId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("lecturer_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<LecturerSubject>(entity =>
        {
            entity.HasKey(e => e.LecturerSubjectId).HasName("PK__Lecturer__E621407CF17AF786");

            entity.ToTable("LecturerSubject");

            entity.Property(e => e.LecturerSubjectId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("lecturer_subject_id");
            entity.Property(e => e.AssignedAt)
                .HasColumnType("datetime")
                .HasColumnName("assignedAt");
            entity.Property(e => e.IsPrincipal).HasColumnName("is_principal");
            entity.Property(e => e.LecturerId)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("lecturer_id");
            entity.Property(e => e.SemesterId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("semester_id");
            entity.Property(e => e.SubjectId)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("subject_id");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Lecturer).WithMany(p => p.LecturerSubjects)
                .HasForeignKey(d => d.LecturerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LecturerS__lectu__5070F446");

            entity.HasOne(d => d.Semester).WithMany(p => p.LecturerSubjects)
                .HasForeignKey(d => d.SemesterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LecturerS__semes__52593CB8");

            entity.HasOne(d => d.Subject).WithMany(p => p.LecturerSubjects)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LecturerS__subje__5165187F");
        });

        modelBuilder.Entity<ScoreColumn>(entity =>
        {
            entity.HasKey(e => e.ColumnId).HasName("PK__ScoreCol__E301851F01951393");

            entity.ToTable("ScoreColumn");

            entity.Property(e => e.ColumnId).HasColumnName("column_id");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Semester>(entity =>
        {
            entity.HasKey(e => e.SemesterId).HasName("PK__Semester__CBC81B019CF2FE3B");

            entity.ToTable("Semester");

            entity.Property(e => e.SemesterId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("semester_id");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Student__2A33069A0275A9C7");

            entity.ToTable("Student");

            entity.HasIndex(e => e.Email, "UQ__Student__AB6E6164E0EDF09D").IsUnique();

            entity.Property(e => e.StudentId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("student_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subject__5004F66049D8CD3E");

            entity.ToTable("Subject");

            entity.Property(e => e.SubjectId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("subject_id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}