// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class Assignment
{
    public Guid AssignmentId { get; set; }

    public string Name { get; set; }

    public string FilePath { get; set; }

    public DateTime? SubmissionDate { get; set; }

    public DateTime? Deadline { get; set; }

    public string Status { get; set; }

    public Guid StudentId { get; set; }

    public Guid ExamId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<GradingResult> GradingResults { get; set; } = new List<GradingResult>();

    public virtual Student Student { get; set; }
}