// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class ExamGradingCriterion
{
    public int CriteriaId { get; set; }

    public string ExamId { get; set; }

    public int ColumnId { get; set; }

    public decimal MaxMark { get; set; }

    public string Description { get; set; }

    public virtual ScoreColumn Column { get; set; }

    public virtual Exam Exam { get; set; }
}