// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

[Table("Exams")]
public partial class Exam
{
    [Key]
    public Guid ExamId { get; set; } = Guid.NewGuid(); // Đổi sang Guid

    public Guid SubjectId { get; set; } // Đổi sang Guid
    public Guid SemesterId { get; set; } // Đổi sang Guid

    [Required]
    [StringLength(255)]
    public string ExamName { get; set; }

    [Required]
    [StringLength(20)]
    public string ExamType { get; set; }

    [StringLength(50)]
    public string ExamPassword { get; set; }

    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("SubjectId")]
    public virtual Subject Subject { get; set; }

    [ForeignKey("SemesterId")]
    public virtual Semester Semester { get; set; }

    public virtual ICollection<TeacherAssignment> TeacherAssignments { get; set; } = new List<TeacherAssignment>();
    public virtual ICollection<Criteria> Criteria { get; set; } = new List<Criteria>();
    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}