// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

public partial class Exam
{
    public Guid ExamId { get; set; }

    public string Title { get; set; }

    public string FilePath { get; set; }

    public string ExtractedPath { get; set; }

    public DateTime? UploadedAt { get; set; }

    public Guid LecturerSubjectId { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? CreatedAt { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();

    public virtual ICollection<ExamGradingCriterion> ExamGradingCriteria { get; set; } = new List<ExamGradingCriterion>();

    public virtual ICollection<ExamKeyword> ExamKeywords { get; set; } = new List<ExamKeyword>();

    public virtual LecturerSubject LecturerSubject { get; set; }
}