// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class ExamKeyword
{
    public Guid ExamKeywordId { get; set; }

    public Guid ExamId { get; set; }

    public Guid KeywordId { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Keyword Keyword { get; set; }
}