// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class GradingDetail
{
    public Guid DetailId { get; set; }

    public Guid ScoreId { get; set; }

    public Guid ColumnId { get; set; }

    public decimal? Mark { get; set; }

    public virtual ScoreColumn Column { get; set; }

    public virtual GradingResult Score { get; set; }
}