// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

public partial class GradingResult
{
    public Guid ResultId { get; set; }

    public decimal? TotalMark { get; set; }

    public DateTime? CheckedAt { get; set; }

    public string Note { get; set; }

    public Guid LecturerId { get; set; }

    public Guid AssignmentId { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? CreatedAt { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? UpdatedAt { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual ICollection<GradingDetail> GradingDetails { get; set; } = new List<GradingDetail>();

    public virtual Lecturer Lecturer { get; set; }
}