// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class GradingResult
{
    public string ResultId { get; set; }

    public decimal? TotalMark { get; set; }

    public DateTime? CheckedAt { get; set; }

    public string Note { get; set; }

    public string LecturerId { get; set; }

    public string AssignmentId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Assignment Assignment { get; set; }

    public virtual ICollection<GradingDetail> GradingDetails { get; set; } = new List<GradingDetail>();

    public virtual Lecturer Lecturer { get; set; }
}