//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace EzyFix.DAL.Models;

//public partial class Keyword
//{
//    public Guid KeywordId { get; set; }

//    public string Word { get; set; }

//    public virtual ICollection<ExamKeyword> ExamKeywords { get; set; } = new List<ExamKeyword>();
//}