// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class LecturerSubject
{
    public string LecturerSubjectId { get; set; }

    public string LecturerId { get; set; }

    public string SubjectId { get; set; }

    public string SemesterId { get; set; }

    public bool? IsPrincipal { get; set; }

    public DateTime? AssignedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual Lecturer Lecturer { get; set; }

    public virtual Semester Semester { get; set; }

    public virtual Subject Subject { get; set; }
}