// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

public partial class LecturerSubject
{
    public Guid LecturerSubjectId { get; set; }

    public Guid LecturerId { get; set; }

    public Guid SubjectId { get; set; }

    public Guid SemesterId { get; set; }

    public bool? IsPrincipal { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? AssignedAt { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual Lecturer Lecturer { get; set; }

    public virtual Semester Semester { get; set; }

    public virtual Subject Subject { get; set; }
}