//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;

//namespace EzyFix.DAL.Models;

//public partial class ScoreColumn
//{
//    public Guid ColumnId { get; set; }

//    public string Name { get; set; }

//    public string Description { get; set; }

//    public virtual ICollection<ExamGradingCriterion> ExamGradingCriteria { get; set; } = new List<ExamGradingCriterion>();

//    public virtual ICollection<GradingDetail> GradingDetails { get; set; } = new List<GradingDetail>();
//}