// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

[Table("Semesters")]
public partial class Semester
{
    [Key]
    public Guid SemesterId { get; set; } = Guid.NewGuid(); // Đổi sang Guid

    [Required]
    [StringLength(20)]
    public string SemesterCode { get; set; }

    [StringLength(100)]
    public string SemesterName { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}