// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

[Table("Students")]
public partial class Student
{
    [Key]
    public Guid StudentId { get; set; } = Guid.NewGuid();

    [Required]
    [StringLength(20)]
    public string StudentMSSV { get; set; }

    [Required]
    [StringLength(255)]
    public string FullName { get; set; }

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}