// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EzyFix.DAL.Models;

public partial class Subject
{
    public Guid SubjectId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<LecturerSubject> LecturerSubjects { get; set; } = new List<LecturerSubject>();
}