// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EzyFix.DAL.Models;

public partial class Subject
{
    [Key]
    public Guid SubjectId { get; set; } = Guid.NewGuid(); // Đổi sang Guid

    [Required]
    [StringLength(20)]
    public string SubjectCode { get; set; }

    [Required]
    [StringLength(255)]
    public string SubjectName { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}