// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EzyFix.DAL.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string LecturerCode { get; set; }

    public bool EmailConfirmed { get; set; }

    public bool? IsActive { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? CreatedAt { get; set; }
    [Column(TypeName = "timestamp with time zone")]
    public DateTime? UpdatedAt { get; set; }

    public Guid? RoleId { get; set; }

    public virtual Role Role { get; set; }

    //public virtual ICollection<GradingResult> GradingResults { get; set; } = new List<GradingResult>();

    //public virtual ICollection<LecturerSubject> LecturerSubjects { get; set; } = new List<LecturerSubject>();
    public virtual ICollection<TeacherAssignment> TeacherAssignments { get; set; } = new List<TeacherAssignment>();
    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
    public virtual ICollection<Violation> Violations { get; set; } = new List<Violation>();
}