// <auto-generated />
using System;
using EzyFix.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EzyFix.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023142626_UpdateUserAndRoleName")]
    partial class UpdateUserAndRoleName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EzyFix.DAL.Models.Assignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("ExamId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__DA891814051AD56B");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Exam", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("ExtractedPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("extracted_path");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("LecturerSubjectId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploadedAt");

                    b.HasKey("ExamId")
                        .HasName("PK__Exam__9C8C7BE9527237D6");

                    b.HasIndex("LecturerSubjectId");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.ExamGradingCriterion", b =>
                {
                    b.Property<Guid>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("criteria_id");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("column_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExamId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<decimal>("MaxMark")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("max_mark");

                    b.HasKey("CriteriaId")
                        .HasName("PK__ExamGrad__401F949D6CCF0428");

                    b.HasIndex("ColumnId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamGradingCriteria");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.ExamKeyword", b =>
                {
                    b.Property<Guid>("ExamKeywordId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("examKeyword_id");

                    b.Property<Guid>("ExamId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.HasKey("ExamKeywordId")
                        .HasName("PK__ExamKeyw__F9DC44C9DA869D2D");

                    b.HasIndex("ExamId");

                    b.HasIndex("KeywordId");

                    b.ToTable("ExamKeyword", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.GradingDetail", b =>
                {
                    b.Property<Guid>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("detail_id");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("column_id");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("mark");

                    b.Property<Guid>("ScoreId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("score_id");

                    b.HasKey("DetailId")
                        .HasName("PK__GradingD__38E9A224518CE962");

                    b.HasIndex("ColumnId");

                    b.HasIndex("ScoreId");

                    b.ToTable("GradingDetail", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.GradingResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<Guid>("AssignmentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkedAt");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("TotalMark")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("total_mark");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ResultId")
                        .HasName("PK__GradingR__AFB3C316C9F23B79");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("UserId");

                    b.ToTable("GradingResult", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Keyword", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("word");

                    b.HasKey("KeywordId")
                        .HasName("PK__Keyword__03E8D7CFE5EF6E0C");

                    b.ToTable("Keyword", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.LecturerSubject", b =>
                {
                    b.Property<Guid>("LecturerSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_subject_id");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignedAt");

                    b.Property<bool?>("IsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_principal");

                    b.Property<Guid>("SemesterId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<Guid>("SubjectId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LecturerSubjectId")
                        .HasName("PK__Lecturer__E621407CF17AF786");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("LecturerSubject", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__760965CC");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.ScoreColumn", b =>
                {
                    b.Property<Guid>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("column_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("ColumnId")
                        .HasName("PK__ScoreCol__E301851F01951393");

                    b.ToTable("ScoreColumn", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Semester", b =>
                {
                    b.Property<Guid>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__CBC81B019CF2FE3B");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__2A33069A0275A9C7");

                    b.HasIndex(new[] { "Email" }, "UQ__Student__AB6E6164E0EDF09D")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subject__5004F66049D8CD3E");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LecturerCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Assignment", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.Exam", "Exam")
                        .WithMany("Assignments")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__exam___59063A47");

                    b.HasOne("EzyFix.DAL.Models.Student", "Student")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__stude__5812160E");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Exam", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.LecturerSubject", "LecturerSubject")
                        .WithMany("Exams")
                        .HasForeignKey("LecturerSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam__lecturer_s__534D60F1");

                    b.Navigation("LecturerSubject");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.ExamGradingCriterion", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.ScoreColumn", "Column")
                        .WithMany("ExamGradingCriteria")
                        .HasForeignKey("ColumnId")
                        .IsRequired()
                        .HasConstraintName("FK__ExamGradi__colum__571DF1D5");

                    b.HasOne("EzyFix.DAL.Models.Exam", "Exam")
                        .WithMany("ExamGradingCriteria")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__ExamGradi__exam___5629CD9C");

                    b.Navigation("Column");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.ExamKeyword", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.Exam", "Exam")
                        .WithMany("ExamKeywords")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__ExamKeywo__exam___5441852A");

                    b.HasOne("EzyFix.DAL.Models.Keyword", "Keyword")
                        .WithMany("ExamKeywords")
                        .HasForeignKey("KeywordId")
                        .IsRequired()
                        .HasConstraintName("FK__ExamKeywo__keywo__5535A963");

                    b.Navigation("Exam");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.GradingDetail", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.ScoreColumn", "Column")
                        .WithMany("GradingDetails")
                        .HasForeignKey("ColumnId")
                        .IsRequired()
                        .HasConstraintName("FK__GradingDe__colum__5CD6CB2B");

                    b.HasOne("EzyFix.DAL.Models.GradingResult", "Score")
                        .WithMany("GradingDetails")
                        .HasForeignKey("ScoreId")
                        .IsRequired()
                        .HasConstraintName("FK__GradingDe__score__5BE2A6F2");

                    b.Navigation("Column");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.GradingResult", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.Assignment", "Assignment")
                        .WithMany("GradingResults")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK__GradingRe__assig__5AEE82B9");

                    b.HasOne("EzyFix.DAL.Models.User", "User")
                        .WithMany("GradingResults")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GradingRe__lectu__59FA5E80");

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.LecturerSubject", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.Semester", "Semester")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK__LecturerS__semes__52593CB8");

                    b.HasOne("EzyFix.DAL.Models.Subject", "Subject")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__LecturerS__subje__5165187F");

                    b.HasOne("EzyFix.DAL.Models.User", "User")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__LecturerS__lectu__5070F446");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.User", b =>
                {
                    b.HasOne("EzyFix.DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Assignment", b =>
                {
                    b.Navigation("GradingResults");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Exam", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ExamGradingCriteria");

                    b.Navigation("ExamKeywords");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.GradingResult", b =>
                {
                    b.Navigation("GradingDetails");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Keyword", b =>
                {
                    b.Navigation("ExamKeywords");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.LecturerSubject", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.ScoreColumn", b =>
                {
                    b.Navigation("ExamGradingCriteria");

                    b.Navigation("GradingDetails");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Semester", b =>
                {
                    b.Navigation("LecturerSubjects");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Student", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.Subject", b =>
                {
                    b.Navigation("LecturerSubjects");
                });

            modelBuilder.Entity("EzyFix.DAL.Models.User", b =>
                {
                    b.Navigation("GradingResults");

                    b.Navigation("LecturerSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
