-- Drop AcademicService tables in correct order
DROP TABLE IF EXISTS "Violations" CASCADE;
DROP TABLE IF EXISTS "Grades" CASCADE;
DROP TABLE IF EXISTS "TeacherAssignments" CASCADE;
DROP TABLE IF EXISTS "Submissions" CASCADE;
DROP TABLE IF EXISTS "Criteria" CASCADE;
DROP TABLE IF EXISTS "Exams" CASCADE;
DROP TABLE IF EXISTS "Students" CASCADE;
DROP TABLE IF EXISTS "Subjects" CASCADE;
DROP TABLE IF EXISTS "Semesters" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;
